export { default as XpBar } from './ui/XpBar.vue'
export { default as StreakCounter } from './ui/StreakCounter.vue'
export { default as AchievementBadge } from './ui/AchievementBadge.vue'
export { default as StudentXpGain } from './ui/StudentXpGain.vue'
export { default as StudentBadgeCard } from './ui/StudentBadgeCard.vue'
export { default as StudentLevelBadge } from './ui/StudentLevelBadge.vue'
export { default as StudentProgressBar } from './ui/StudentProgressBar.vue'
export { default as StudentLeaderboard } from './ui/StudentLeaderboard.vue'
export { default as GemCounter } from './ui/GemCounter.vue'
export { default as StreakCalendar } from './ui/StreakCalendar.vue'
export { default as LevelUpModal } from './ui/LevelUpModal.vue'
export { useGameProfile } from './composables/useGameProfile'
export type { GameProfile, XPTransaction, GemTransaction, Achievement, StudentAchievement, ShopItem, StudentInventory } from './model/types'
export { ACHIEVEMENT_CATEGORY_ICONS } from './model/types'
